name: Docker Hub Login Test

on:
  workflow_dispatch  # allows you to run this manually from GitHub UI

jobs:
  test-login:
    runs-on: ubuntu-latest
    steps:
      - name: Test Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
